# Generated by Django 5.1.1 on 2024-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inuser_date_of_birth_inuser_gender_inuser_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuser',
            name='phone_num',
            field=models.IntegerField(null=True),
        ),
    ]
