# Generated by Django 5.1.1 on 2024-10-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_inuser_date_of_birth_remove_inuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inuser',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
