# Generated by Django 5.1.1 on 2024-10-09 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_inuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuser',
            name='image',
            field=models.ImageField(default='profile_pics/blank-profile-picture-973460_1280.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='inuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
