# Generated by Django 5.1.1 on 2024-10-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_inuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuser',
            name='about',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
