# Generated by Django 5.1.1 on 2024-10-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photoes'),
        ),
    ]
