# Generated by Django 5.1.1 on 2024-10-05 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='C',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
