# Generated by Django 5.1.1 on 2024-10-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
