# Generated by Django 5.1.1 on 2024-11-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
